-- YOUSEF IBRAHIM GOMAA MAHMOUD - DEPI SESSION 3
------
-- DDL CREATE,DROP,ALTER !!AUTO COMMITTED!!
-- CREATE TABLE EMPLOYEE(
-- FNAME VARCHAR(25) NOT NULL,
-- LNAME VARCHAR(25) NOT NULL,
-- SSN INT PRIMARY KEY,
-- BDATE DATE NOT NULL,
-- ADDRESS VARCHAR(50) NOT NULL,
-- SEX CHAR(1),
-- SALARY FLOAT(10) NOT NULL,
-- SUPERSSN INT,
-- DNO INT
-- );

 --DROP TABLE students;

--CREATE TABLE students(
--ID INT PRIMARY KEY);

--ALTER TABLE students ADD address VARCHAR(25);
--ALTER TABLE students DROP COLUMN address;

-- ALTER TABLE students ADD fname VARCHAR(25);
--ALTER TABLE students ALTER COLUMN fname VARCHAR(25) NOT NULL;

--SELECT * FROM students;

--INSERT INTO students (ID, age, fname) VALUES (1, 21, 'AHMED');

-- DML INSERT,UPDATE,DELETE,SELECT

